// import "./globals.css";
// import { Toaster } from "@/components/ui/toaster";
// const inter = Inter({ subsets: ["latin"] });
// import { Inter } from "next/font/google";
// import AuthProvider from "@/context/AuthProvider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// import { ThemeProvider } from "@/components/theme-provider";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
// import { AppSidebar } from "@/components/ui/app-sidebar";


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning={true}>
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//       </head>
      
//       <body className={inter.className}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <AuthProvider>
//             {children}
//             <Toaster />
//           </AuthProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


import ClientLayout from "./ClientLayout";
import "./globals.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
